# Number of days of inactivity before an issue becomes stale
# three month plus one weekend plus two more workdays 31+30+31+2+2=96
daysUntilStale: 96
# Number of days of inactivity before a stale issue is closed
# two weeks plus one weekend plus two more workdays 7+7+2+2=18
daysUntilClose: 18
# Issues with these labels will never be considered stale
exemptLabels:
  - Dedicated Priority Support
  - critical/security bug
  - severe improvement
  - blocker
# Label to use when marking an issue as stale
staleLabel: ready-to-close?
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
   This issue has been automatically marked as stale
   because it has not had recent activity for three month.
   It will be closed if no further activity occurs within two weeks.
   Thank you for your contribution.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
